### ISSUE TITLE
Talk to A-frame team about Mozfest

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#1]
It would be great to have the A-frame team attend, and if not, maybe they have some good ideas on how we can integrate VR experiences into our space. I'll talk to Kip who may have some suggestions.

**Comment by mwakaswanga** [comment]
who are the A-frame team?

**Comment by flukeout** [comment]
Aframe is mozilla's Web VR authoring tool, you can check it out here - https://aframe.io/
You can create VR scenes using a sort of markup language like HTML, so it's great for beginners.

One of the engineers on that team works at the Vancouver office where I am, so I'll talk to him about getting involved in the Web Literacy Space in some way.

**Comment by mwakaswanga** [comment]
This is awesome, you have a network of very great people :-)

**Comment by edovio** [comment]
@flukeout great to know! I know some volunteers from the Mozilla Campus Club program that done yet resources about that, and Mozilla TechSpeaker that are made yet some Talks about WebVR. Let me know if will be helpful and I start to ping other people.

**Comment by flukeout** [comment]
Hey yeah that would be cool @edovio - should we wait until the call for proposals?

**Comment by edovio** [comment]
I think not if we want to collect feedback about our ideas. I think will be helpful know first about what could be made for our space with this technology.
At these links some activities made for the Activate campaign and for the Campus Club:
https://activate.mozilla.community/webvr-camp/ 
https://mozillacampusclubs.github.io/Build-a-Virtual-World/

**Comment by flukeout** [comment]
Discussions in progress.
