### ISSUE TITLE
Revisit role assignments, and make sure we're still OK with the roles that we took on.

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#13]
For reference, here's an etherpad with some of the role descriptions that was shared by Sarah and Erika in our last wrangler called.

* https://public.etherpad-mozilla.org/p/festival.roles2017

Here's [our original planning doc](https://docs.google.com/document/d/12rpJ4XkOHL2FTMkNeErBJFk6W-gMaJUd1smwFzlxjMk/edit) from our time in Tallinn. Let's all review the roles we chose and make sure we are still able to take them on.

**Comment by edovio** [comment]
have you figure out when do this activity? At our next call? or when?

**Comment by ArtsAward** [comment]
I've reviewed the roles that we outlines, I'm still happy with those I am assigned to, and the key drivers too.
