### ISSUE TITLE
Write blog posts describing our space & vision to support open call.

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#14]

**Comment by edovio** [comment]
Interesting. We can create a Blog post multi language. I can invite to help us to localize the content the Brazilian, French, Italian, German & Spanish Mozilla Communities. Moreover, I want to write a blog post in my blog concerning our space ;)

**Comment by ArtsAward** [comment]
I have scheduled a blog post from Arts Award which can then be re posted on the Mozfest pages on 26th June then later to generally promote the festival on 14 Aug and 18 Sept

**Comment by edovio** [comment]
Okay but the calls for proposal will open today :) So it's important an massive promotion now :) not later :)

**Comment by flukeout** [comment]
I've started a draft [here](https://docs.google.com/document/d/1fUFOYQcQ7iQHglEvhimWxltRuRYlIwD8VYNh2HrmnLc/edit) - everyone should have access.

**Comment by ArtsAward** [comment]
I've left you my comments on the google doc @flukeout :)

**Comment by flukeout** [comment]
Closing as it's been written & shared!
