### ISSUE TITLE
Help spread the Open Call for Proposals.

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#15]
The open call for proposals will be going out in just a few days. Let's use this issue to let each other know what we call can do to spread the call as far and as wide as we can.

We'll receive more details from Sarah and Erika soon.

**Comment by flukeout** [comment]
For me, I can...

* Promote to call to action on the Thimble homepage
  * Filed in https://github.com/mozilla/mozfest-web-literacy/issues/10
* Tweet it out on the @mozlearning account that the Foundation uses

**Comment by ArtsAward** [comment]
I will be blogging from Arts Award, also using our social media and twitter pages, I'll also be making a direct approach to all those who delivered sessions for us in 2016

**Comment by mwakaswanga** [comment]
It will be shared on all [DOT Tanzania](https://tanzania.dotrust.org/) social networks platforms, I will also share with our (DOT Tanzania) youths and tech partners.
