### ISSUE TITLE
Assign leads for Shed, Gallery and Classroom areas?

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#16]
Mozfest sessions will fall into three categories. It was suggested that maybe we can organize ourselves in a way where some of us are the point person for each particular space and give it more thought, here's an attempt at that.

* **The Shed** - Hands on learning and making
  * @flukeout
* **The Classroom** - Lectures, discussions and knowledge sharing
  * @edovio or @mwakaswanga?
* **The Gallery** - Some kind of art exhibit
  * @MarianaDelgadoG?

What does everyone think about that. It might help us when we are going through the proposals.

**Comment by edovio** [comment]
for me it's okay ;)

**Comment by ArtsAward** [comment]
Good for me, happy to collaborate on both the Shed and the Gallery

**Comment by mwakaswanga** [comment]
Okay for me as well.

**Comment by MarianaDelgadoG** [comment]
Thank you so much Luke! I'm happy to work for the Gallery, and also to help
with the Classroom.

Best,
M.

**Comment by PhillipaBailey** [comment]
I'm okay with collaborating on both the shed and gallery

**Comment by MarianaDelgadoG** [comment]
Hi all!

I'm at Mozfest Slacker, but I don't see anyone else? Is there any other
link?
Best,

M.



2017-06-03 9:17 GMT-05:00 PhillipaBailey <notifications@github.com>:
