### ISSUE TITLE
Write wrangler Bios (and provide photo) for Mozfest site & printed program.

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#17]
We've got to write a 50 word bio for the Mozfest Website and submit a high-res photo of ourselves by Monday, July 24th.

* [Submit them to this Spreadsheet](https://docs.google.com/spreadsheets/d/1RyDQ1BF3gYLMj9Koy9gqEbB_LQoQQa0opVLfOgNzt_I/edit#gid=0)

**Comment by flukeout** [comment]
cc @edovio @ArtsAward @mwakaswanga @MarianaDelgadoG @jonathanprozzi

**Comment by edovio** [comment]
I just started to put something in the Spreadsheet. I nees only to see if
is good what I wrote and a good HQ photo xD

Il 21 Lug 2017 22:32, "Luke Pacholski" <notifications@github.com> ha
scritto:
