### ISSUE TITLE
To-Do Summary from Aug 7 Call

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#18]
Here's what's left to do

* Finish reviewing first pass of sessions
  * [x] Jonathan
  * [x] Luke
  * [x] Julie
  * Let's make sure we add a _Youth Friendly or Youth Led_ indicator for Julie
* [x] Send email to people who requested stipend but are not on github - Luke
* [ ] Figure out how many stipends we have to give away - Julie?
* Review [Secondary Space - Web Lit](https://github.com/MozillaFoundation/mozfest-program-2017/issues?q=is%3Aopen+is%3Aissue+label%3A%22%5BSecondary+Space%5D+Web+Literacy%22) sessions
  * [ ] Mariana
  * [x] Edoardo
  * [ ] Fredie

**Comment by edovio** [comment]
As we decided yesterday I take the Sessions in page 1,2 and the first five in the page 7. 
I put all the information in our spreadsheet.

**Comment by flukeout** [comment]
Thanks @edovio I'll check it out later today!
