### ISSUE TITLE
Add ideas to pinterest board for space design

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#2]
It would be good to start brainstorming some some ideas for space design. Pinterest might be a good option but we can discuss options. Maybe a Google Slides deck.

**Comment by ArtsAward** [comment]
I am pinterest.com/julielarner

**Comment by flukeout** [comment]
Im https://www.pinterest.com/luke0269/

**Comment by PhillipaBailey** [comment]
I'm pinterest.com/phillipabailey2 i have started a mozfest space design board

**Comment by edovio** [comment]
Im https://www.pinterest.com/edovio/

**Comment by flukeout** [comment]
Here's the link to the board:
* https://www.pinterest.com/phillipabailey2/mozfest-space-ideas/

**Comment by edovio** [comment]
Guys, let me know when we want to start to create some Design draft for the space :) So I will start to create somethings :)
