### ISSUE TITLE
Talk to Robert (or past wranglers) about their experiences last year

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#3]
Robert wrangled the Web Lit space last year and might have some good insight:

* What worked?
* What was the best session?
* What didn't?
* What would he have done differently, etc?
* Did he get any feedback from attendees?

**Comment by ArtsAward** [comment]
Julie is talking to Su Adams this Thursday about her involvement last year and if she wants to be involved again

**Comment by edovio** [comment]
Today I talked with Julia Vallera (Moziilla clubs Program), and, I asked to give us some feedback about their experience as Wrangler. The same at three volunteers who helped in the space. If is good for all of us, I can ask at they to come here and give an answer at all these questions in this issue. :)

**Comment by edovio** [comment]
I'm sorry because I thought to put the link yet in the repo. I Created some days ago an etherpad where the volunteer of the last year put their feedback of the MozFest 2016. The link is: https://public.etherpad-mozilla.org/p/mozFest2016WebLiteracyFeedback
