### ISSUE TITLE
Talk to Mozilla Clubs Volunteer at last year's space

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#5]
Edoardo knows someone that was involved, and will check in:

* What aspects and sessions was successful?
* What needed improvement or re-thinking?
* Feedback from attendees?

**Comment by edovio** [comment]
Today I started to write something in a couple of Telegram Channels about the last MozFest and the mozilla clubs. I want to know who are involved and next we can consider to have a call with they and ask some question or, if all of you prefer, I can collect their feedback and i will put in a new document. Moreover, I pinged, Julia Vallera to collect information from she too.

**Comment by flukeout** [comment]
Hey @edovio - yeah go ahead and collect whatever information you can get. I spoke with Robert Friedman today who was involved last year in the Demistify The Web space and got some good info from him. Particularly check out this cool blog post about their space:

https://medium.com/mozilla-festival/making-teaching-and-learning-more-inviting-dcedfd4a9580

**Comment by edovio** [comment]
I created an etherpad to collect some feedback at this address: https://public.etherpad-mozilla.org/p/mozFest2016WebLiteracyFeedback 
You can share with all people you want! :)

**Comment by edovio** [comment]
I sent the link at Julia and two volunteers that are involved last year!
