### ISSUE TITLE
Finalize Space Description

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#6]
We've got some ideas in our [doc here](https://docs.google.com/document/d/12rpJ4XkOHL2FTMkNeErBJFk6W-gMaJUd1smwFzlxjMk/edit) but need to get this finalized.

**Comment by flukeout** [comment]
If I'm writing a coment and i want to tag someone @ArtsAward

**Comment by flukeout** [comment]
Here's the latest draft...

> The web is like a garden that we all plant and eat from. We have to be considerate about what we sow as well as what, and how much, we consume. In the Web Literacy space, we’ll dig into the set of skills that help us read, write and participate on the web in a way that enriches both it, and ourselves.
>
> Through making, experimenting, hearing from experts and through play, people of all ages can develop their skills and create a better, more vibrant web. You’ll be empowered to explore your digital world, grow your confidence and gain inspiration from others.
>
> Whether you’re at the start of your digital journey, an everyday user or teaching others new skills, you’ll find sessions that engage and inspire.

The working version (along with option 2) in the [this document](https://docs.google.com/document/d/1Q_VfTqsW6zOSNZhD18wXo-frFSvEaZ2IPEwJf84x7Lg/edit).

We agreed to go with the "Garden" version, so let's refine that one.

**Comment by edovio** [comment]
I agree with @flukeout to go with the "Garden" Version. I love this: 
The web is like a garden that we all plant and eat from. We have to be considerate about what we sow as well as what, and how much, we consume. In the Web Literacy space, we’ll dig into the set of skills that help us read, write and participate on the web in a way that enriches both it, and ourselves.

**Comment by flukeout** [comment]
**Some notes from the Call**

* The main goal of the description is to attract people who would want to host sessions
* To get them excited about the goal and mission of the space and help themselves see playing a role in accomplishing that through sharing their skills, experience & knowledge

**Due by** May 12th!

**Comment by flukeout** [comment]
Haha thanks @edovio

**Comment by PhillipaBailey** [comment]
The Garden one is definitely the better of the two

**Comment by ArtsAward** [comment]
I really like the draft by @flukeout  too.  It's already at 126 words and I was just about to suggest that we added a few hints in about the types of sessions we are looking for!  Word counts are so mean!  Maybe we can somehow squeeze in a line that says something like: 
From the Internet of Things of finding out about creative coding and design for the web, there's sure to be sessions to inspire visitors of all ages.

**Comment by flukeout** [comment]
Hey @ArtsAward - if you have some time today, please go ahead and take a crack at an updated description. I'm planning to do some more edits tonight after work and will submit it by end of day. Thanks!

Here's [the doc](https://docs.google.com/document/d/1Q_VfTqsW6zOSNZhD18wXo-frFSvEaZ2IPEwJf84x7Lg/edit).

**Comment by flukeout** [comment]
Okay, so, this is what I submitted...

> The web is like a garden that we all plant and eat from. We need to consider what we sow as well as what, and how much, we consume. In the Web Literacy space, we’ll dig into the set of skills that help us read, write and participate on the web in a way that enriches both it, and ourselves.
>
> In hands-on workshops, participants will explore, make and play with the tools and technologies that form the fabric of the web. Through discussion and talks, we’ll invite our guests to reflect on, and improve, their relationship to the web.
>
> Our space will instill the skills and confidence in both young and old, students and teachers, to make the web a more vibrant, diverse ecosystem.

**Comment by edovio** [comment]
Hello everyone! 
I just read the description :) For me is good !:)  I'm happy! From the first drafts done by all of us at the mozRetreat all are grown and come to be what I just wrote! :) Yeah!!!

**Comment by ArtsAward** [comment]
Sounding great, thank you very much for doing this @flukeout

**Comment by flukeout** [comment]
Okay, closing as the space description is finalized & submitted.
