### ISSUE TITLE
Write Open Call copy to attract session hosts

### ISSUE THREAD

**Issue by flukeout** [mozilla/mozfest-web-literacy#7]
We'll get more clarity on this, but in addition to our space description, we'll need some copy to entice and attract session hosts/leaders to our space.

**Questions**
* What channels will this be going out in?
  * Twitter? Blog?

**To Consider**
* Any particular types of content or topics we want to attract?

**Comment by flukeout** [comment]
It's done!

**Comment by ArtsAward** [comment]
To answer the above, generally it goes out on the Mozfest website and later on in the festival brochure.  the social media channels just signpost to that page on the website.
We will also be invited to separately blog about our space, this will be a good opportunity for us to get some extra promo out, we can do this several times. Might be nice for a few of us to do this to get a few perspectives in different blogs.  This all helps with the June/July promo around the call out for submissions.

**Comment by edovio** [comment]
Hello everyone,
So I will use all the channel of all the communities that I lead here in Italy (Mozilla Italia, Mozilla Cagliari Club) and I will spread our voice over all the Mozilla programs where I'm involved, in particular, in our next Mozilla Clubs leader call i will present our ideas and I want to collect feedback and engage people to promote our space in their communities. (The Mozilla Club program is the Mozilla program in real nearest our space -> https://learning.mozilla.org/en-US/clubs)

**Comment by edovio** [comment]
Concerning the Social Media I think is helpful to spread our voice in all the platform as Facebook, Instagram and Twitter ecc ecc... I'm available to do that on Twitter, Facebook and Instagram. If any of you know and use another Social Website is better to plan how define a strategy of engagement over these channel. We can talk with Sierra to promote our space over the official Mozilla Instagram Account (mozillagram) too

**Comment by ArtsAward** [comment]
Hey @flukeout how you doing with the final narrative?  Do you want any last minute help?

**Comment by flukeout** [comment]
Closing this issue as the copy has been drafted now and we'll be starting to promote it soon.
